[discovery_extension_definition]

short_name = pandorafms.vmware_vcenter_pyvmomi_summary_v2
section = app
name = VMware vCenter pyVmomi Summary v2
version = "2.0"
description = VMware vCenter summary modules + VM summary table via pyVmomi. TLS verify disabled.

; Script utama yang akan dijalankan oleh Discovery Server.
; Di dalam .disco nanti kita sertakan file "scan_vmware_api.py" ini.
execution_file[_exec1_] = "pandorafms_vcenter_pyvmomi_summary_v2.py"

; Perintah yang dijalankan setiap kali task Discovery dieksekusi.
; Sesuaikan /usr/bin/python3 kalau `which python3` kamu beda.
exec[] = "/usr/bin/python3 _exec1_ -H '_host_' -u '_user_' -p '_password_' -A '_agent_' -g '_group_' -v --outdir '__incomingDir__' --run-log '_runlog_' --status-file '__temp__/__taskMD5__-vmware-pyvmomi-summary-v2-status.json'"

; Nilai default untuk beberapa field
default_value[_group_]  = VMware
default_value[_runlog_] = /var/log/pandora-scan/scan_vmware_pyvmomi_summary.run.log

; ============================================================
;  FORM KONFIGURASI DISCOVERY
; ============================================================

[config_steps]

; Hanya satu langkah konfigurasi sederhana
name[1]           = vCenter connection
custom_fields[1]  = vmware_basic
fields_columns[1] = 2


[vmware_basic]

; 1) vCenter Host/IP
macro[1]       = _host_
name[1]        = vCenter Host/IP
type[1]        = string
placeholder[1] = 10.10.6.250

; 2) Username
macro[2]       = _user_
name[2]        = Username
type[2]        = string
placeholder[2] = PandoraFMS@vsphere.local

; 3) Password
macro[3] = _password_
name[3]  = Password
type[3]  = password

; 4) Agent name
macro[4]       = _agent_
name[4]        = Agent name
type[4]        = string
placeholder[4] = DC-MCStack-Cluster

; 5) Agent group (pakai daftar group agent di Pandora)
macro[5]       = _group_
name[5]        = Agent group
type[5]        = select
select_data[5] = agent_groups

; 6) Run log path (opsional)
macro[6]          = _runlog_
name[6]           = Run log path
type[6]           = string
required_field[6] = false
placeholder[6]    = /var/log/pandora-scan/scan_vmware_api.run.log

